/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogsRouteImport } from './routes/catalogs'
import { Route as EnquiriesResolvedRouteImport } from './routes/enquiries-resolved'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductsAdminRouteImport } from './routes/products-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogsRoute = CatalogsRouteImport.update({
  id: '/catalogs',
  path: '/catalogs',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiriesResolvedRoute = EnquiriesResolvedRouteImport.update({
  id: '/enquiries-resolved',
  path: '/enquiries-resolved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsAdminRoute = ProductsAdminRouteImport.update({
  id: '/products-admin',
  path: '/products-admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogs': typeof CatalogsRoute
  '/enquiries-resolved': typeof EnquiriesResolvedRoute
  '/products': typeof ProductsRoute
  '/products-admin': typeof ProductsAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogs': typeof CatalogsRoute
  '/enquiries-resolved': typeof EnquiriesResolvedRoute
  '/products': typeof ProductsRoute
  '/products-admin': typeof ProductsAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogs': typeof CatalogsRoute
  '/enquiries-resolved': typeof EnquiriesResolvedRoute
  '/products': typeof ProductsRoute
  '/products-admin': typeof ProductsAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/catalogs' | '/enquiries-resolved' | '/products' | '/products-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/catalogs' | '/enquiries-resolved' | '/products' | '/products-admin'
  id:
    | '__root__'
    | '/'
    | '/catalogs'
    | '/enquiries-resolved'
    | '/products'
    | '/products-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogsRoute: typeof CatalogsRoute
  EnquiriesResolvedRoute: typeof EnquiriesResolvedRoute
  ProductsRoute: typeof ProductsRoute
  ProductsAdminRoute: typeof ProductsAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogs': {
      id: '/catalogs'
      path: '/catalogs'
      fullPath: '/catalogs'
      preLoaderRoute: typeof CatalogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiries-resolved': {
      id: '/enquiries-resolved'
      path: '/enquiries-resolved'
      fullPath: '/enquiries-resolved'
      preLoaderRoute: typeof EnquiriesResolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products-admin': {
      id: '/products-admin'
      path: '/products-admin'
      fullPath: '/products-admin'
      preLoaderRoute: typeof ProductsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogsRoute: CatalogsRoute,
  EnquiriesResolvedRoute: EnquiriesResolvedRoute,
  ProductsRoute: ProductsRoute,
  ProductsAdminRoute: ProductsAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
